// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhyXKRnVDa_N3ln_Lyh9ZzJIO8lIdHAFo',
    appId: '1:253365573816:web:016f72988fd05af14b3c4d',
    messagingSenderId: '253365573816',
    projectId: 'recepies-app-jdh',
    authDomain: 'recepies-app-jdh.firebaseapp.com',
    storageBucket: 'recepies-app-jdh.firebasestorage.app',
    measurementId: 'G-W8VKSZPCL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfzkzoQR0zEggnAdKRIHUzR6Xa00hF3J4',
    appId: '1:253365573816:android:e02226792a9294a94b3c4d',
    messagingSenderId: '253365573816',
    projectId: 'recepies-app-jdh',
    storageBucket: 'recepies-app-jdh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCGy2Qbt6KcuvhaiB2XSrFXebyY8eT_M',
    appId: '1:253365573816:ios:e065c1fe3d7d3c3a4b3c4d',
    messagingSenderId: '253365573816',
    projectId: 'recepies-app-jdh',
    storageBucket: 'recepies-app-jdh.firebasestorage.app',
    iosBundleId: 'com.example.receipesApp',
  );
}
